### ISSUE TITLE
totem of regen

### ISSUE THREAD

**Issue by codeRG7122** [chronosacaria/MCDungonesArtifacts#11]
the totem of regen sometimes works but doesn't and it makes particles but doesn't heal me 
1.18.1

**Comment by codeRG7122** [comment]
1.18.1

**Comment by Kluzzio** [comment]
I'm unable to recreate this issue. Can you please provide a list of mods as this is most likely a mod compatibility issue. Thanks!

**Comment by Kluzzio** [comment]
Some additional information would also be fantastic. When you say that it doesn't heal you, the totem just gives the regeneration effect. Are you getting this effect? Are you not healing to vanilla max health, or are you not healing to an altered max health? Thanks!
