### ISSUE TITLE
[Bug Report]: Using artifacts crashes client

### ISSUE THREAD

**Issue by kineticV** [chronosacaria/MCDungonesArtifacts#23]
### Describe the bug; What happened?

The client crashes when right clicking on a held artifact. I tried this months ago and it didn't happen, everything worked fine.

I tested this with the wind horn, feather, and boots of swiftness.  The same thing happened with all of these. The server remains active when this happens and I can reconnect, but the client stops.

Error logs are printed in the server but not the client. In the session with the logs I right clicked on an artifact. The client crashed. I restarted the client and then right clicked on a different artifact. The client crashed again.

### Expected Behavior

The client shouldn't crash.

### Mod Version

1.5.2-1.18

### Minecraft Launcher

MultiMC

### Operating System

Windows

### Modpack

Custom

### Additional context

Server logs (there are no error logs on the client): https://pastebin.com/cDTdC8TT

**Comment by chronosacaria** [comment]
@kineticV This issue does not appear to be present when just MCDAR is installed as I cannot reproduce this issue. Please consider a binary search on your modlist to see what could be causing the issue. There really isn't anything that jumps out at me as immediately being the likely cause of the issue. I would start by removing mods that are in Alpha or Beta, first, though, such as Twilight Forest. Alpha and Beta mods are going to be more likely to cause issues by virtue of the fact that they are not finished yet

**Comment by chronosacaria** [comment]
Due to lack of response and the inability to reproduce this issue, it shall be closed
