### ISSUE TITLE
[Enhancement]: Please make Beast Enchantments work with Wolves and other non-summoned pets

### ISSUE THREAD

**Issue by BurntTrashFor** [chronosacaria/MCDungonesArtifacts#25]
### Describe the bug; What happened?

Drinking healing potions does nothing.

### Expected Behavior

Explosion/buffs on the pet

### Mod Version

1.5.2

### Minecraft Launcher

Other

### Operating System

Windows

### Additional context

Fabric*

**Comment by chronosacaria** [comment]
@BurntTrashFor We need more information. What is the pet you're trying to buff? Do you have a log that you can provide? If you do, we can check to see if there is some kind of conflict happening. Do you have other mods installed? Are you using TLauncher?

Please answer all of these questions so we can better assist you

**Comment by BurntTrashFor** [comment]
> @BurntTrashFor We need more information. What is the pet you're trying to buff? Do you have a log that you can provide? If you do, we can check to see if there is some kind of conflict happening. Do you have other mods installed? Are you using TLauncher?
> 
> Please answer all of these questions so we can better assist you
-Pet is Vanilla MC Wolf
-idk where to find logs
-Tested in single player with nothing but MCDAR and it's dependencies
-no I am not using Tlauncher, I am using the basic Minecraft Launcher(idk what you would call it)
I tried both normal and splash potion of healing and it doesn't seem to do anything. Other enchants from the MCDungeons series works fine.

**Comment by BurntTrashFor** [comment]
Found where the logs are, 
[latest.log](https://github.com/chronosacaria/MCDungeonsArtifacts/files/10684456/latest.log)

**Comment by chronosacaria** [comment]
@BurntTrashFor Ah, okay, I see what's going on. So, at this time, the Beast Enchantments only work on _summoned_ pets, not wolves. We can look into this, but at this time, this is functioning as intended. I shall change the title of this to indicate that it is an enhancement request
