### ISSUE TITLE
[Bug Report]: Some Texts are Missing

### ISSUE THREAD

**Issue by muhammedesadcomert** [chronosacaria/MCDungonesArtifacts#27]
### Describe the bug; What happened?

Summoned creatures' names are missing. Probably they are not in the lang files.

![2023-04-14_20 02 16](https://user-images.githubusercontent.com/46245749/232112149-738f352d-6658-4cff-893f-ad9c3d5be147.png)

![2023-04-14_20 10 57](https://user-images.githubusercontent.com/46245749/232112200-32bdc30f-1234-4d00-9402-00527149c500.png)

### Expected Behavior

Those names should have been; Tasty Bone Wolf, and Golem Kit Golem or something like that.

### Mod Version

1.5.3

### Minecraft Launcher

Other

### Operating System

Windows

**Comment by chronosacaria** [comment]
This is because of a mod conflict. Please look into which mods you're using to see which might be messing with langs or caching stuff incorrectly
