### ISSUE TITLE
No name for wheat_lama. Looks weird with Waila, Jade and other mode like this

### ISSUE THREAD

**Issue by ghost** [chronosacaria/MCDungonesArtifacts#30]
### Is your feature request related to a problem? Please describe.

It's just would be better if it had name instead of programming things
![2023-05-03_09 01 41](https://user-images.githubusercontent.com/124847943/235803658-3c3c59bb-4ae1-4700-be74-27660ce9e4fa.png)

### Describe the solution you'd like

The name "Wheat Lama" is ok for that creature

**Comment by chronosacaria** [comment]
@variety754 This is definitely coming from a mod incompatibility. This doesn't happen with just MCDAR and its dependencies. Could you share your mod list, please?

**Comment by ghost** [comment]
Of course. How do you want me to send this list for you?

**Comment by ghost** [comment]
[modlist.txt](https://github.com/chronosacaria/MCDungeonsArtifacts/files/11379031/modlist.txt)
All the mods from this list have latest version for 1.19.3 installed except for indium and sodium extra

**Comment by chronosacaria** [comment]
@variety754 That's perfect! I'll take a look at this this weekend. Thanks for such a quick response :)

**Comment by ghost** [comment]
So it's fixed for 1.20 but on 1.19.3 fix will not be ported?

**Comment by chronosacaria** [comment]
Only 1.20 is being supported. Only game breaking bug fixes will be backported
