### ISSUE TITLE
[Feature Request]: Implement Tameable into the "Beast" Features

### ISSUE THREAD

**Issue by fzzyhmstrs** [chronosacaria/MCDungonesArtifacts#35]
### Is your feature request related to a problem? Please describe.

_We had a bit of a discussion on this in a stream, I'm formalizing it here:_

Your current "Beast" system utilizes `Summonable` to do checks and pass owner info. Per my current understanding, this means that only MCDAR-summoned mobs are affected by "Beast" enchantments.

### Describe the solution you'd like

I think it'd be nice if these enchantments affected anything with the `Tameable` interface either alongside or in place of `Summonable`. This would allow vanilla wolves etc. to be affected, as well as other summons.

In particular, all of the AI summons now utilize `Tameable` to categorize them into a "I summoned this mob" category (alongside my _own_ interface, `PlayerCreatable`). Having Beast Burst etc. affect Hamsters, Unhallowed, and so on, would be a fun bit of dependency-free mod interaction, in my opinion.

### Additional context

I also have my own `Beast Master` totem augment now, as a nod to the "Beast" effects in MCDAR. That augment checks for `Tameable`. Would be fun if the interaction extended both ways and worked on MCDAR summons as well.

**Comment by chronosacaria** [comment]
Ah,thanks for posting this @fzzyhmstrs! You know how my memory is lol
