### ISSUE TITLE
[Feature Request]: modify values for artifacts

### ISSUE THREAD

**Issue by Ricenami** [chronosacaria/MCDungonesArtifacts#37]
### Is your feature request related to a problem? Please describe.

Hi, I love your mods. I was wondering if you could provide datapack support/config support to modify and change some values with the artifacts. I feel like most of the artifacts are really underwhelming in modded MC and I would love to edit the values to give them more use.

I would appreciate any feedback.

Cheers!

### Describe the solution you'd like

Add Datapack/Config Support for values. (ex: cooldown, how far you jump with light feather, damage for blast fungus, etc.)

**Comment by chronosacaria** [comment]
@Ricenami That seems like quite a reasonable ask. We can definitely look into that 🙂
