### ISSUE TITLE
[Feature Request]: Modrinth

### ISSUE THREAD

**Issue by yavko** [chronosacaria/MCDungonesArtifacts#39]
### Is your feature request related to a problem? Please describe.

I can't download it easily

### Describe the solution you'd like

Adding the mod to modrinth

### Additional context

All the other MCDungeons mods are on modrinth

**Comment by chronosacaria** [comment]
@yavko We need to do an update to MCDAR to fix a rare crash. We didn't want to upload the one with this bug to Modrinth. Once we fix it, we'll be uploading it

**Comment by yavko** [comment]
> @yavko We need to do an update to MCDAR to fix a rare crash. We didn't want to upload the one with this bug to Modrinth. Once we fix it, we'll be uploading it

Wow, that was quick, thanks for the details though
