### ISSUE TITLE
Beast Burst + Wandering Trader Crash

### ISSUE THREAD

**Issue by Raavea** [chronosacaria/MCDungonesArtifacts#4]
Hi there,
  I've got better wandering traders and your MC Dungeons mods (and over 100 others!), and just experienced a crash. I tried removing the trader mod but still experienced the crash, so I tried removing your mod after googling beast burst and it no longer crashes on load.

 Please see attached:

> ---- Minecraft Crash Report ----
> // Daisy, daisy...
> 
> Time: 7/23/21, 9:08 AM
> Description: Ticking entity
> 
> java.lang.ClassCastException: class net.minecraft.class_3989 cannot be cast to class net.minecraft.class_1657 (net.minecraft.class_3989 and net.minecraft.class_1657 are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @141e5bef)
> 	at net.minecraft.class_1309.handler$cdl000$onBeastBurstPotionConsumption(class_1309.java:26657)
> 	at net.minecraft.class_1309.method_6040(class_1309.java)
> 	at net.minecraft.class_1309.method_37119(class_1309.java:2952)
> 	at net.minecraft.class_1309.method_6076(class_1309.java:2939)
> 	at net.minecraft.class_1309.method_5773(class_1309.java:2305)
> 	at net.minecraft.class_1308.method_5773(class_1308.java:338)
> 	at net.minecraft.class_3218.method_18762(class_3218.java:656)
> 	at net.minecraft.class_1937.method_18472(class_1937.java:483)
> 	at net.minecraft.class_3218.method_31420(class_3218.java:418)
> 	at net.minecraft.class_5574.method_31791(class_5574.java:54)
> 	at net.minecraft.class_3218.method_18765(class_3218.java:393)
> 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:893)
> 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:833)
> 	at net.minecraft.class_1132.method_3748(class_1132.java:96)
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:692)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274)
> 	at java.base/java.lang.Thread.run(Thread.java:831)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Server thread
> Stacktrace:
> 	at net.minecraft.class_1309.handler$cdl000$onBeastBurstPotionConsumption(class_1309.java:26657)
> 	at net.minecraft.class_1309.method_6040(class_1309.java)
> 	at net.minecraft.class_1309.method_37119(class_1309.java:2952)
> 	at net.minecraft.class_1309.method_6076(class_1309.java:2939)
> 
> -- Patchouli Book Info --
> Details:
> 	Patchouli open book context: n/a
> Stacktrace:
> 	at net.minecraft.class_128.handler$bpe000$fillPatchouliContext(class_128.java:521)
> 	at net.minecraft.class_128.<init>(class_128.java:36)
> 	at net.minecraft.class_128.method_560(class_128.java:266)
> 	at net.minecraft.class_1937.method_18472(class_1937.java:485)
> 	at net.minecraft.class_3218.method_31420(class_3218.java:418)
> 	at net.minecraft.class_5574.method_31791(class_5574.java:54)
> 	at net.minecraft.class_3218.method_18765(class_3218.java:393)
> 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:893)
> 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:833)
> 	at net.minecraft.class_1132.method_3748(class_1132.java:96)
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:692)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274)
> 	at java.base/java.lang.Thread.run(Thread.java:831)
> 
> -- Entity being ticked --
> Details:
> 	Entity Type: minecraft:wandering_trader (net.minecraft.class_3989)
> 	Entity ID: 262
> 	Entity Name: Lore Deitering the Wandering Trader
> 	Entity's Exact location: -332.17, 65.00, 326.51
> 	Entity's Block location: World: (-333,65,326), Section: (at 3,1,6 in -21,4,20; chunk contains blocks -336,0,320 to -321,255,335), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Entity's Momentum: 0.00, -0.08, 0.00
> 	Entity's Passengers: []
> 	Entity's Vehicle: null
> 
> -- Affected level --
> Details:
> 	All players: 1 total; [class_3222['Etheiy'/261, l='ServerLevel[0.28]', x=-331.06, y=30.00, z=321.45]]
> 	Chunk stats: 2445
> 	Level dimension: minecraft:overworld
> 	Level spawn location: World: (-64,74,240), Section: (at 0,10,0 in -4,4,15; chunk contains blocks -64,0,240 to -49,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Level time: 226404 game time, 348710 day time
> 	Level name: 0.28
> 	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
> 	Level weather: Rain time: 115450 (now: false), thunder time: 155725 (now: false)
> 	Known server brands: fabric
> 	Level was modded: true
> 	Level storage version: 0x04ABD - Anvil
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.17
> 	Minecraft Version ID: 1.17
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 16.0.1, Microsoft
> 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
> 	Memory: 2277507072 bytes (2172 MiB) / 4844421120 bytes (4620 MiB) up to 6442450944 bytes (6144 MiB)
> 	CPUs: 12
> 	Processor Vendor: GenuineIntel
> 	Processor Name: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
> 	Identifier: Intel64 Family 6 Model 158 Stepping 10
> 	Microarchitecture: Coffee Lake
> 	Frequency (GHz): 2.21
> 	Number of physical packages: 1
> 	Number of physical CPUs: 6
> 	Number of logical CPUs: 12
> 	Graphics card #0 name: NVIDIA Quadro P3200
> 	Graphics card #0 vendor: NVIDIA (0x10de)
> 	Graphics card #0 VRAM (MB): 4095.00
> 	Graphics card #0 deviceId: 0x1bbb
> 	Graphics card #0 versionInfo: DriverVersion=27.21.14.6259
> 	Graphics card #1 name: Intel(R) UHD Graphics 630
> 	Graphics card #1 vendor: Intel Corporation (0x8086)
> 	Graphics card #1 VRAM (MB): 1024.00
> 	Graphics card #1 deviceId: 0x3e9b
> 	Graphics card #1 versionInfo: DriverVersion=30.0.100.9684
> 	Memory slot #0 capacity (MB): 16384.00
> 	Memory slot #0 clockSpeed (GHz): 2.67
> 	Memory slot #0 type: DDR4
> 	Virtual memory max (MB): 48966.34
> 	Virtual memory used (MB): 18619.63
> 	Swap memory total (MB): 32768.00
> 	Swap memory used (MB): 946.43
> 	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6144m -Xms256m -XX:PermSize=256m
> 	Fabric Mods: 
> 		additionalbars: Additional Bars 2.0.5
> 		advancedcompass: Advanced Compass 1.2.1
> 		alloy_forgery: Alloy Forgery 1.3.2
> 		ambientenvironment: Ambient Environment fabric-1.17.1-6.0.13
> 		animal_feeding_trough: Animal Feeding Trough 1.0.2
> 		apoli: Apoli 1.0.4
> 		aqupdgrizzly: Grizzly Bear mob 1.1.1
> 		architects_palette: Architect's Palette Fabric 1.2
> 		architectury: Architectury 2.2.21
> 		bannerpp: Banner++ 2.0.3+mc.1.17-rc1
> 		bclib: BCLib 0.2.3
> 		bedspreads: Bedspreads 1.4.0-1.17
> 		better_withered_mobs: Better Withered Mobs 1.6.0
> 		betterdroppeditems: Better Dropped Items 1.3.0-1.17
> 		betterend: Better End 0.10.5-pre
> 		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.0
> 		betternether: Better Nether 5.1.3
> 		betterstrongholds: YUNG's Better Strongholds 1.17-1.1
> 		biome_locator: Biome Locator 1.1.2
> 		blockus: Blockus 2.2.6+1.17.1
> 		blue_endless_jankson: jankson 1.2.1
> 		calio: Calio 1.0.2
> 		canvas: Canvas Renderer 1.0.1802
> 		cardinal-components-base: Cardinal Components API (base) 3.0.0
> 		cardinal-components-chunk: Cardinal Components API (chunks) 3.0.0
> 		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
> 		cavebiomes: Cave Biomes 0.6.3
> 		charm: Charm 3.3.0
> 		chickendropfeathers: Chicken Drop Feathers 1.0
> 		cloth-api: Cloth API 2.0.54
> 		cloth-basic-math: Cloth Basic Math 0.5.1
> 		cloth-client-events-v0: Cloth Client Events v0 2.0.54
> 		cloth-common-events-v1: Cloth Common Events v1 2.0.54
> 		cloth-config2: Cloth Config v4 5.0.34
> 		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
> 		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
> 		cloth-utils-v1: Cloth Utils v1 2.0.54
> 		clumps: Clumps fabric-1.17.1-7.0.4
> 		com_electronwill_night-config_core: core 3.6.2
> 		com_electronwill_night-config_toml: toml 3.6.2
> 		com_moandjiezana_toml_toml4j: toml4j 0.7.2
> 		comforts: Comforts 0.0.4-1.17
> 		croptopia: Croptopia 1.5.0
> 		cullleaves: Cull Leaves 2.2.0
> 		dark-loading-screen: Dark Loading Screen 1.6.5
> 		dawn: Dawn API 2.0.3
> 		diggusmaximus: Diggus Maximus 1.4.5-1.17
> 		dynmus: Dynamic Music 1.3.1
> 		eldritch_mobs: Eldritch Mobs 1.9.0
> 		enchant_giver: Enchant Giver 1.1.0
> 		entitybanners: Entity Banners 1.0.1-BETA+1.17
> 		entityculling: EntityCulling-Fabric 1.3.3
> 		expandedstorage: Expanded Storage 7.0.0-alpha.33
> 		fabric: Fabric API 0.36.0+1.17
> 		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
> 		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d03d
> 		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
> 		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
> 		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
> 		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
> 		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
> 		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
> 		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
> 		fabric-diagonal-panes: Fabric Diagonal Panes 0.5.0
> 		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
> 		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
> 		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c03d
> 		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
> 		fabric-furnaces: Fabric Furnaces 2.0.1-1.17
> 		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
> 		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
> 		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
> 		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b44633d
> 		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
> 		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
> 		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
> 		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
> 		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
> 		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
> 		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab6121d5
> 		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
> 		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
> 		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
> 		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
> 		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
> 		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
> 		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
> 		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
> 		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
> 		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
> 		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
> 		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
> 		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
> 		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
> 		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
> 		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
> 		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
> 		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
> 		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
> 		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
> 		fabricloader: Fabric Loader 0.11.6
> 		fallflyinglib: FallFlyingLib 3.0.0-beta.2
> 		fallingleaves: Falling Leaves 1.7.2+1.17
> 		fallingtree: FallingTree 2.12.1
> 		fermion: Fermion 2.11.243
> 		fermion-modkeys: Fermion Modifier Keys 1.10.241
> 		fermion-orientation: Fermion Orientation 1.2.243
> 		fermion-varia: Fermion Varia 2.6.243
> 		fiber: fiber 0.23.0-2
> 		flytre_lib: FlytreLib 0.2.18
> 		frex: FREX 5.2.225
> 		geckolib3: Geckolib 3.0.8
> 		greater_eye: Greater Eye of Ender 1.2.5
> 		grondag_bitraster: bitraster 1.4.12
> 		herdspanic: Herds Panic 1.0.2
> 		illuminations: Illuminations 1.6.2
> 		impaled: Impaled 1.0.1
> 		improved-stations: Improved Stations 2.0.6
> 		incantationem: Incantationem 1.1
> 		inmis: Inmis 2.3.1-1.17
> 		inventorysorter: Inventory Sorter 1.7.9-1.17
> 		jankson: Jankson 3.0.1+j1.2.0
> 		java: OpenJDK 64-Bit Server VM 16
> 		json-model-extensions: JSON Model Extensions 1.22.201
> 		kirin: Kirin UI 1.8.7-1.17
> 		kubejs: KubeJS 1605.3.10-build.9999
> 		kyrptconfig: Kytpt Config 1.1.10-1.17
> 		lacrimis: Lacrimis 2.1.2+1.17
> 		lambdabettergrass: LambdaBetterGrass 1.2.0+1.17
> 		lambdynlights: LambDynamicLights 2.0.1+1.17
> 		libcd: LibCapableData 3.0.3+1.16.3
> 		linkedstorage: Linked Storage 1.3.11-1.17
> 		lithium: Lithium 0.7.3
> 		lovely_snails: Lovely Snails 1.0.2+1.17
> 		magna: Magna 1.5.5-1.17-pre4
> 		maybe-data: Maybe data 1.0.1-1.17
> 		mcda: MC Dungeons Armors 1.7.5
> 		mcdar: MC Dungeons Artifacts 1.4.0
> 		mcdw: MC Dungeons Weapons 3.2.4
> 		midnightlib: MidnightLib 0.2.2
> 		minecraft: Minecraft 1.17
> 		mo_glass: Mo Glass 1.5-MC1.17
> 		moborigins: Mob Origins 1.6.0
> 		modmenu: Mod Menu 2.0.3
> 		mooblooms: Mooblooms 1.5.0
> 		more_gems: More Gems 1.2.26
> 		moreberries: More Berries 1.4.2
> 		morevillagers-fabric: MoreVillagersFabric 2.0.4-SNAPSHOT
> 		mostructures: Mo' Structures 1.2.1-1.17
> 		notforgotten: Not Forgotten 1.0.0
> 		npcvariety: NPC Variety 2.1.2
> 		omega-config: OmegaConfig 1.0.8
> 		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
> 		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
> 		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
> 		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
> 		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
> 		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
> 		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
> 		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
> 		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
> 		origins: Origins 1.0.3
> 		origins-classes: Origins: Classes 1.2.2
> 		patchouli: Patchouli 1.17-54-FABRIC
> 		pipe: Pipe 1.3.1
> 		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
> 		presencefootsteps: Presence Footsteps r31-1.17-rc1
> 		promenade: Promenade 2.1.2
> 		puddles: Puddles 1.1.0
> 		pugh_tools: Pugh Tools ${version}
> 		quartzelv: Quartz Elevator 1.2.5
> 		ratsmischief: Rat's Mischief 1.2
> 		reach-entity-attributes: Reach Entity Attributes 2.1.1
> 		reborncore: Reborn Core 5.0.3-beta+build.55
> 		respackopts: Resource Pack Options 2.1.1
> 		respawnablepets: Respawnable Pets 1.17-2
> 		rhino: Rhino 1605.1.1-build.23
> 		rocks: This Rocks! 1.4.0
> 		rotten: FleshZ 1.4.2
> 		roughlyenoughitems: Roughly Enough Items 6.0.264-alpha
> 		rpgz: RPGZ 0.4.8
> 		seasons: Fabric Seasons 1.2.2-BETA+1.17
> 		shulkerutils: shulkerutils 1.0.1-1.17
> 		somnus: Somnus API 0.0.12-1.17
> 		special-circumstances: Special Circumstances 1.9.243
> 		spruceui: SpruceUI 3.2.0+1.17
> 		static-content: Static Content 1.0.1-1.16.2
> 		staticdata: Static Data 1.1.2
> 		stoneholm: Stoneholm 1.2.7
> 		team_reborn_energy: Energy 0.1.1
> 		techreborn: Tech Reborn 5.0.3-beta+build.55
> 		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
> 		things: Things 0.2.1
> 		transportables: Transportables 1.0.5
> 		trinkets: Trinkets 3.0.0
> 		universal_ores: Universal Ores 1.0
> 		untitledduckmod: Untitled Duck Mod 0.3.0
> 		upgradedechests: Upgraded Ender Chests 1.0.2-1.17
> 		urns: Urns 1.0.1
> 		vanilla-hammers: Vanilla Hammers 3.1.2-1.17
> 		vanillaexcavators: Vanilla Excavators 1.1.0
> 		villagernames: Villager Names 2.0.0
> 		waystones: Waystones 2.0.1
> 		whereisit: Where Is It 1.13.3
> 		wildfire_gender: Wildfire's Female Gender Mod 2.6.1
> 		woods_and_mires: Woods and Mires 1.1.0+1.17
> 		worldedit: WorldEdit 7.2.6-beta-01+1415e6f
> 		wrenchable: Wrenchable 1.1.0+1.17
> 		wthit: wthit 3.7.0
> 		xaerominimap: Xaero's Minimap 21.14.0
> 		xaeroworldmap: Xaero's World Map 1.15.0.1
> 		yungsapi: YUNG's API 1.17-Fabric-13
> 	Player Count: 1 / 8; [class_3222['Etheiy'/261, l='ServerLevel[0.28]', x=-331.06, y=30.00, z=321.45]]
> 	Data Packs: vanilla, Fabric Mods
> 	Type: Integrated Server (map_client.txt)
> 	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by chronosacaria** [comment]
Thank you for posting this. I am working on fixing this :)
