### ISSUE TITLE
[Bug Report]: Game crashing when using Thundering Quiver against a pig

### ISSUE THREAD

**Issue by SimplyChloe** [chronosacaria/MCDungonesArtifacts#41]
### Describe the bug; What happened?

Game crashed when projectile shot with Thundering Quiver landed on pig (how specific lol). Seems to work fine on other mobs.

### Expected Behavior

Expected:
Using Thundering quiver and shooting it at a pig should strike them with lighting and transform them into zombie piglin.
(I was using the quiver on the shield slot which seems to be the only place where it works. Idk if this is intended or accidental)
![image](https://github.com/chronosacaria/MCDungeonsArtifacts/assets/105401445/88ab6922-9cf4-47aa-9ca3-a13f9cf1e54e)

### Mod Version

4.0.1

### Minecraft Launcher

Other

### Operating System

Windows

**Comment by chronosacaria** [comment]
@JustRyan362 So the offhand slot is definitely where it should be, but it shouldn't crash when trying to turn the pig into a zombie piglin. Could you post your crash report, please, and edit your title to have the issue in it?

**Comment by SimplyChloe** [comment]
[latest.log](https://github.com/chronosacaria/MCDungeonsArtifacts/files/14748063/latest.log)
I've attached the log of the crash here. I should also add that I have quite some extra mods, but I don't think none of them affects the game is rendered (had to remove sodium and iris due to a bug with Immersive portals) and none of the mods affects the way arrows or bows work as far as I know.
